### ISSUE TITLE
use ignite

### ISSUE THREAD

**Issue by hipstersmoothie** [bowbahdoe/andrew_site#1]
gitbook is trash. no plugin system! and the older version has like es3 plugin system ;) you trying to implement something?

**Comment by bowbahdoe** [comment]
This is for my brother. He wants to publish non technical stuff. Plugin system matters zero when going through the cycles of "I want to write something", "you never will because you are lazy", "no I just dont have X", "gives X", (sounds of counter strike)

**Comment by bowbahdoe** [comment]
Also, Ill switch to ignite for stuff when I get the energy and motivation to fix the windows bugs

```
C:\Users\Ethan\Development\blog>npx ignite -w
Command failed: C:\"Program Files"\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js config get cache --parseable
module.js:491
    throw err;
    ^

Error: Cannot find module 'C:\Program'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3

Command failed: C:\"Program Files"\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js config get cache --parseable
module.js:491
    throw err;
    ^

Error: Cannot find module 'C:\Program'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3
```
